server:
  port: 8088

auth0:
  issuer: "https://kids-first.auth0.com/"
  apiAudience: "https://kf-release-coord.kidsfirstdrc.org"

release-coordinator:
  url: https://kf-release-coord-qa.kidsfirstdrc.org
  # used to make secure REST calls to release coordinator
  auth:
    enable: false

rollcall:
  url: http://localhost:8080
  # used to make secure REST calls to rollcall
  auth:
    enable: true

docker:
  image:
    useLocal: true
  # This can be a tag (if useLocal == false) or an imageId (if useLocal == true)
    id: <docker images | head -2 | tail -1>
  network:
    id: default
  driver:
    memory: 1g
  executor:
    memory: 1g
  input:
    conf: <path to kf_etl.conf file>
