server:
  port: 1234

auth:
  jwt:
    publicKeyUrl: "http://localhost:8081/oauth/token/public_key"

docker:
  useLocal: true
  # This can be a tag (if useLocal == false) or an imageId (if useLocal == true)
  imageId: <docker images | head -2 | tail -1>
  input:
    conf: <path to kf_etl.conf file>
    jar: <path to kf-portal-etl.jar file>
