server:
  port: 1234

auth:
  jwt:
    publicKeyUrl: "http://localhost:8081/oauth/token/public_key"

docker:
  image:
    useLocal: true
  # This can be a tag (if useLocal == false) or an imageId (if useLocal == true)
    id: <i.e: docker images | head -2 | tail -1>
  network:
    id: default
  input:
    conf: <path to kf_etl.conf file>
    jar: <path to kf-portal-etl.jar file>
